
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

# SEO Improvements - Set custom headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://api.supabase.co https://cfjibduhagxiwqkiyhqd.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content"
    Permissions-Policy = "camera=(), geolocation=(), microphone=()"
    X-Robots-Tag = "index, follow"

# Simplified redirects - Reduced from original file
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true
