
# Base configuration for Netlify
[build]
  command = "npm run build"
  publish = "dist"

# Headers to improve security and performance
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Configuration CSP très permissive pour résoudre les problèmes d'authentification
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; connect-src * https://*.supabase.co wss://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src * data: blob:; font-src * data:; frame-src *;"
    # Headers CORS très permissifs
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# Force HTTPS avec priorité maximale
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Redirection prioritaire de streamgenius.fr vers streamgenius.io
[[redirects]]
  from = "https://streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Redirection www vers non-www
[[redirects]]
  from = "https://www.streamgenius.io/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Configuration de proxy direct pour Supabase Auth
[[redirects]]
  from = "/.supabase/auth/*"
  to = "https://cfjibduhagxiwqkiyhqd.supabase.co/auth/v1/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"

# Configuration de proxy direct pour Supabase REST
[[redirects]]
  from = "/.supabase/rest/*"
  to = "https://cfjibduhagxiwqkiyhqd.supabase.co/rest/v1/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"

# Configuration de redirection spécifique pour l'authentification
[[redirects]]
  from = "/auth/v1/*"
  to = "https://cfjibduhagxiwqkiyhqd.supabase.co/auth/v1/:splat"
  status = 200
  force = true

# Configuration de redirection spécifique pour l'API REST
[[redirects]]
  from = "/rest/v1/*"
  to = "https://cfjibduhagxiwqkiyhqd.supabase.co/rest/v1/:splat"
  status = 200
  force = true

# Configuration spéciale pour le callback d'authentification
[[redirects]]
  from = "/supabase-auth-callback"
  to = "/login"
  status = 200
  force = true

# Configuration spéciale pour les callbacks storage
[[redirects]]
  from = "/storage/v1/*"
  to = "https://cfjibduhagxiwqkiyhqd.supabase.co/storage/v1/:splat"
  status = 200
  force = true

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
