
# Configuration Netlify pour streamgenius.io
[build]
  command = "npm run build"
  publish = "dist"

# Headers pour résoudre les problèmes CORS et CSP
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Client-Info, apikey, X-Supabase, x-supabase-auth"
    Access-Control-Max-Age = "86400"
    Access-Control-Allow-Credentials = "true"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; connect-src * https://*.supabase.co wss://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src * data: blob:; font-src * data:; frame-src *; worker-src 'self' blob:;"
    X-Content-Type-Options = "nosniff"

# Configurations spéciales pour l'authentification avec priorité maximale
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
  from = "/auth/callback/*"
  to = "/index.html"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }
  
[[redirects]]
  from = "/api/auth/*"
  to = "/index.html"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

# Redirection HTTPS avec priorité maximale
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Redirection des domaines .fr vers .io avec priorité maximale
[[redirects]]
  from = "https://streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Redirection www vers non-www avec priorité maximale
[[redirects]]
  from = "https://www.streamgenius.io/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Routes cruciales pour la navigation
[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login/*"
  to = "/index.html"
  status = 200
  force = true

# Configuration spéciale pour le proxy Supabase
[[redirects]]
  from = "/.supabase/*"
  to = "https://cfjibduhagxiwqkiyhqd.supabase.co/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.rest/*"
  to = "https://cfjibduhagxiwqkiyhqd.supabase.co/rest/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/.auth/*"
  to = "https://cfjibduhagxiwqkiyhqd.supabase.co/auth/:splat"
  status = 200
  force = true

# Fallback pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
