
# Base configuration for Netlify
[build]
  command = "npm run build"
  publish = "dist"

# Headers to improve security and performance
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Élargissement du CSP pour autoriser toutes les connexions API nécessaires
    Content-Security-Policy = "default-src 'self' https://cfjibduhagxiwqkiyhqd.supabase.co https://*.supabase.co; script-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co https://api.supabase.co wss://*.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; frame-ancestors 'none';"

# Force HTTPS avec priorité maximale
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Redirection prioritaire de streamgenius.fr vers streamgenius.io
[[redirects]]
  from = "https://streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Redirection www vers non-www
[[redirects]]
  from = "https://www.streamgenius.io/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
