
# Base configuration for Netlify
[build]
  command = "npm run build"
  publish = "dist"

# Headers to improve security and performance
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://api.supabase.co https://cfjibduhagxiwqkiyhqd.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; frame-ancestors 'none'; upgrade-insecure-requests;"

# Simple redirect from HTTP to HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Redirect from streamgenius.fr to streamgenius.io
[[redirects]]
  from = "https://streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Handle all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
