
# Configuration Netlify pour résoudre les problèmes d'authentification
[build]
  command = "npm run build"
  publish = "dist"

# Headers pour résoudre les problèmes CORS et CSP
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "86400"
    Access-Control-Allow-Credentials = "true"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; connect-src * https://*.supabase.co wss://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src * data: blob:; font-src * data:; frame-src *;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

# Endpoint spécial pour les tests de santé
[[redirects]]
  from = "/api/health"
  to = "https://cfjibduhagxiwqkiyhqd.supabase.co/auth/v1/health"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

# Configurations spéciales pour l'authentification
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
  from = "/auth/callback/*"
  to = "/index.html"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirection HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Redirection des domaines .fr vers .io
[[redirects]]
  from = "https://streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Redirection www vers non-www
[[redirects]]
  from = "https://www.streamgenius.io/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Routes principales avec fallback SPA
[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
