
# Configuration Netlify optimisée pour l'authentification
[build]
  command = "npm run build"
  publish = "dist"

# Headers pour améliorer la connexion Supabase et CORS
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; connect-src * https://*.supabase.co wss://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src * data: blob:; font-src * data:; frame-src *;"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "authorization, x-client-info, apikey, content-type, content-length, accept, origin, x-requested-with"
    Access-Control-Max-Age = "86400"
    Access-Control-Allow-Credentials = "true"

# Configurations spéciales pour l'authentification
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/callback/*"
  to = "/index.html"
  status = 200

# Redirection HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Redirection des domaines .fr vers .io
[[redirects]]
  from = "https://streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.streamgenius.fr/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Redirection www vers non-www
[[redirects]]
  from = "https://www.streamgenius.io/*"
  to = "https://streamgenius.io/:splat"
  status = 301
  force = true

# Routes principales avec fallback SPA
[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

