
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

# Force HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Access-Control-Allow-Origin = "*"

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Custom error page for 500 responses
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 500

# Force HTTP to HTTPS for all requests
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
