
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://cfjibduhagxiwqkiyhqd.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmamliZHVoYWd4aXdxa2l5aHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTY1NTMsImV4cCI6MjA1NzY5MjU1M30.QRjnxj3RAjU_-G0PINfmPoOWixu8LTIsZDHcdGIVEg4";

// Configuration optimisée pour la production
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false, // Désactivé pour éviter les problèmes de redirection
    storage: localStorage,
    flowType: 'implicit',
    debug: true, // Activer le débogage
  },
  global: {
    headers: {
      'X-Client-Info': 'streamgenius',
      'Content-Type': 'application/json',
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

/**
 * Fonction radicale de nettoyage de toutes les données d'authentification
 * Optimisée pour résoudre les problèmes de connexion persistants
 */
export const clearStoredAuthData = () => {
  try {
    console.log("🧹 Nettoyage radical des données d'authentification");
    
    // Liste des préfixes de clés liées à l'authentification à supprimer
    const authPrefixes = [
      'sb-', 
      'supabase', 
      'auth.',
      'auth_',
      'token',
      'access_token',
      'refresh_token'
    ];
    
    // Identifiant spécifique du projet Supabase à nettoyer
    const projectRef = 'cfjibduhagxiwqkiyhqd';
    
    // Nettoyer les clés spécifiques au projet
    const specificKeys = [
      `sb-${projectRef}-auth-token`,
      `sb-${projectRef}-auth-token-for-integration`,
      `supabase.auth.token`,
      `supabase.auth.refreshToken`,
      `auth.token`,
      `auth_session`,
      `sb-access-token`,
      `sb-refresh-token`,
      'auth_checking',
      'auth_refreshing',
      'auth_redirecting',
      'auth_redirect_timestamp',
      'auth_check_timestamp',
      'auth_retry_count',
      'auth_in_progress'
    ];
    
    // Supprimer les clés spécifiques
    specificKeys.forEach(key => {
      try {
        localStorage.removeItem(key);
        sessionStorage.removeItem(key);
      } catch (e) {
        console.warn(`Impossible de supprimer la clé ${key}`, e);
      }
    });
    
    // Recherche et suppression de toutes les clés correspondant aux préfixes
    let keysToRemove = [];
    
    // Vérification dans localStorage
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && authPrefixes.some(prefix => key.includes(prefix))) {
        keysToRemove.push(key);
      }
    }
    
    // Suppression des clés identifiées
    keysToRemove.forEach(key => {
      try {
        localStorage.removeItem(key);
      } catch (e) {
        console.warn(`Échec de suppression de ${key} dans localStorage`, e);
      }
    });
    
    // Même opération pour sessionStorage
    keysToRemove = [];
    for (let i = 0; i < sessionStorage.length; i++) {
      const key = sessionStorage.key(i);
      if (key && authPrefixes.some(prefix => key.includes(prefix))) {
        keysToRemove.push(key);
      }
    }
    
    keysToRemove.forEach(key => {
      try {
        sessionStorage.removeItem(key);
      } catch (e) {
        console.warn(`Échec de suppression de ${key} dans sessionStorage`, e);
      }
    });
    
    // Suppression complète des cookies liés à l'authentification
    document.cookie.split(';').forEach(cookie => {
      const cookieName = cookie.split('=')[0].trim();
      if (authPrefixes.some(prefix => cookieName.includes(prefix))) {
        document.cookie = `${cookieName}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/;`;
      }
    });
    
    console.log(`Nettoyage des données d'authentification terminé: ${keysToRemove.length} éléments supprimés`);
    return true;
  } catch (err) {
    console.error("Erreur critique lors du nettoyage des données d'authentification:", err);
    return false;
  }
};

/**
 * Fonction de vérification pour s'assurer qu'aucun jeton d'authentification n'existe
 * @returns true si les données sont propres, false sinon
 */
export const verifyAuthDataIsClean = () => {
  try {
    const projectRef = 'cfjibduhagxiwqkiyhqd';
    const tokenKey = `sb-${projectRef}-auth-token`;
    
    return !localStorage.getItem(tokenKey) && !sessionStorage.getItem(tokenKey);
  } catch (e) {
    console.error("Erreur lors de la vérification des données d'authentification:", e);
    return false;
  }
};
